backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "news_data"
    label: "Aktuality"
    files:
      - label: "Všetky aktuality"
        name: "news_list"
        file: "news.json"
        fields:
          - label: "Zoznam aktualít"
            name: "items"
            widget: "list"
            fields:
              - {label: "Názov aktuality", name: "title", widget: "string"}
              - {label: "Dátum", name: "date", widget: "datetime", format: "DD.MM.YYYY", time_format: false}
              - {label: "Fotografia (nepovinné)", name: "image", widget: "image", required: false}
              - {label: "Text aktuality", name: "body", widget: "text"}
