backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "news"
    label: "Aktuality (Новини)"
    folder: "news"
    create: true
    delete: true
    extension: "json"
    format: "json"
    fields:
      - {label: "Заголовок новини", name: "title", widget: "string"}
      - {label: "Дата", name: "date", widget: "date", format: "DD.MM.YYYY"}
      - {label: "Фотографія (необов'язково)", name: "image", widget: "image", required: false}
      - {label: "Текст новини", name: "body", widget: "markdown"}