backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "news"
    label: "Aktuality"
    folder: "news"
    create: true
    delete: true
    extension: "json"
    format: "json"
    fields:
      - {label: "Názov aktuality", name: "title", widget: "string"}
      - {label: "Dátum", name: "date", widget: "date", format: "DD.MM.YYYY"}
      - {label: "Fotografia (nepovinné)", name: "image", widget: "image", required: false}
      - {label: "Text aktuality", name: "body", widget: "markdown"}
